openapi: 3.0.9
info:
  title: Meus Endpoints
  version: '1.0'
servers:
  - url: "https://localhost:7000"
components:
  schemas:
    Usuario:
      properties:
        nome:
          type: string
        senha:
          type: string
        pontos:
          type: number
        latitude:
          type: number
        longitude:
          type: number
paths:
  /usuario:
    post:
      operationId: "criarUsuario"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/model/usuarioSchema.js'
      responses:
        '200':
          description: Usuario criado com sucesso!
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  senha:
                    type: number
                  pontos:
                    type: number
                  latitude:
                    type: number
                  longitude:
                    type: number
        '400':
          description: Erro!
  /reciclagem/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
              $ref: ''
      responses:
        '200':
          description: Listagem de todas as reciclagens do usuario
        '400':
          description: Erro!
        '404':
          description: Id não foi encontrado